/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.io.File;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author win8
 */
public class interfazReserva4 extends javax.swing.JFrame {

    /**
     * Creates new form interfazReserva4
     */
    public interfazReserva4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entradaEstiloFiltro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        entradaCapacidadFiltro = new javax.swing.JTextField();
        entradaPrecioFiltro = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccionar Vehiculo");

        jLabel2.setText("Estilo de Vehiculo:");

        entradaEstiloFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaEstiloFiltroActionPerformed(evt);
            }
        });

        jLabel3.setText("Capacidad:");

        entradaPrecioFiltro.setText("Precio de alquiler diario(menor a mayor)");
        entradaPrecioFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaPrecioFiltroActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(entradaEstiloFiltro)
                            .addComponent(entradaCapacidadFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                        .addGap(85, 85, 85)
                        .addComponent(entradaPrecioFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jButton1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(entradaEstiloFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entradaPrecioFiltro))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(entradaCapacidadFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entradaEstiloFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaEstiloFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaEstiloFiltroActionPerformed

    private void entradaPrecioFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaPrecioFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaPrecioFiltroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTable1.setDefaultRenderer(Object.class, new jTableSelect());
        jTable1.setRowHeight(30);
        //Se crean las botones
        JButton boton = new JButton("Detalles");
        boton.setName("Detalles");
        
        DefaultTableModel modelo =  new DefaultTableModel(){//Para que no se puedan editar los datos de las tablas
            @Override
            public boolean isCellEditable(int row,int column){
                return false;
        }
        };
        modelo.addColumn("Imagen");
        modelo.addColumn("Estilo de Vehiculo");
        modelo.addColumn("Costo por día");
        int contador =0;
        this.jTable1.setModel(modelo);
        //Para agregar datos en la fila
        Object O[]=null;
        //Numero de fila
        
        if(entradaPrecioFiltro.isSelected()==false && (Integer.parseInt(entradaEstiloFiltro.getText()))==0 && (Integer.parseInt(entradaCapacidadFiltro.getText()))==0 ){
                JOptionPane.showMessageDialog(null, "Error al realizar la busqueda, ingrese los filtros deseados", "Error de ingreso",JOptionPane.PLAIN_MESSAGE);}
        else{
            //Filtro solo por la el Tipo de Vehiculo
            if(!"".equals(Integer.parseInt(entradaEstiloFiltro.getText())) && entradaPrecioFiltro.isSelected()==false && entradaCapacidadFiltro.getText().equals("") ){
                PrograBases1.vehiculos.getHead();
                PrograBases1.vehiculos.current = PrograBases1.vehiculos.current.getNextNode();
        
                while(PrograBases1.vehiculos.current != null){
                    //Busca el vehiculo
                    if((Integer.parseInt(entradaEstiloFiltro.getText()))==(PrograBases1.vehiculos.current.getElement().idEstilo )&&
                            interfazReserva3.copiaSedeRecogida == (PrograBases1.vehiculos.current.getElement().idSede)){
                        File imagen = PrograBases1.vehiculos.current.getElement().getFoto();
                        int estilo = PrograBases1.vehiculos.current.getElement().getIdEstilo();
                        int costo = PrograBases1.vehiculos.current.getElement().getCostoDia();
                        
                        modelo.addRow(O);
                        modelo.setValueAt(imagen, contador, 0);
                        modelo.setValueAt(estilo, contador, 1);
                        modelo.setValueAt(costo, contador, 2);
                        modelo.setValueAt(boton, contador, 3);

                        contador =  contador + 1;
                        
                    }PrograBases1.vehiculos.current = PrograBases1.vehiculos.current.getNextNode();
                }
            }
            //Filtro de solo la Capacidad del Vehiculo
            else if(!"".equals(Integer.parseInt(entradaCapacidadFiltro.getText())) && entradaPrecioFiltro.isSelected()==false && entradaEstiloFiltro.getText().equals("") ){
                PrograBases1.vehiculos.getHead();
                PrograBases1.vehiculos.current = PrograBases1.vehiculos.current.getNextNode();
        
                while(PrograBases1.vehiculos.current != null){
                    //Busca el vehiculo
                    if((Integer.parseInt(entradaCapacidadFiltro.getText()))==(PrograBases1.vehiculos.current.getElement().getCantidadPersonas() )&&
                            interfazReserva3.copiaSedeRecogida == (PrograBases1.vehiculos.current.getElement().idSede)){
                        File imagen = PrograBases1.vehiculos.current.getElement().getFoto();
                        int estilo = PrograBases1.vehiculos.current.getElement().getIdEstilo();
                        int costo = PrograBases1.vehiculos.current.getElement().getCostoDia();
                        
                        modelo.addRow(O);
                        modelo.setValueAt(imagen, contador, 0);
                        modelo.setValueAt(estilo, contador, 1);
                        modelo.setValueAt(costo, contador, 2);
                        modelo.setValueAt(boton, contador, 3);

                        contador =  contador + 1;
                        
                    }PrograBases1.vehiculos.current = PrograBases1.vehiculos.current.getNextNode();
                }
            }
            //Filtro solo del precio
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazReserva4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazReserva4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazReserva4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazReserva4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazReserva4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entradaCapacidadFiltro;
    private javax.swing.JTextField entradaEstiloFiltro;
    private javax.swing.JCheckBox entradaPrecioFiltro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
